<?xml version="1.0" encoding="utf-8"?><Database Name="Sky_FitnessDB" Class="SkyFitnessBDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ABELCONSUEGRA;Initial Catalog=Sky_FitnessDB;Integrated Security=True" SettingsObjectName="Sky_Fitness.Properties.Settings" SettingsPropertyName="Sky_FitnessDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Detalle.ClienteInscripcion" Member="ClienteInscripcion">
    <Type Name="ClienteInscripcion">
      <Column Name="idClienteInscripcion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombreUsuario" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="numeroIdentidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idInscripcion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_ClienteInscripcion" Member="Cliente" ThisKey="numeroIdentidad" OtherKey="numeroIdentidad" Type="Cliente" IsForeignKey="true" />
      <Association Name="Usuario_ClienteInscripcion" Member="Usuario" ThisKey="nombreUsuario" OtherKey="nombreUsuario" Type="Usuario" IsForeignKey="true" />
      <Association Name="Inscripcion_ClienteInscripcion" Member="Inscripcion" ThisKey="idInscripcion" OtherKey="idInscripcion" Type="Inscripcion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Detalle.ClienteProducto" Member="ClienteProducto">
    <Type Name="ClienteProducto">
      <Column Name="idClienteProducto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombreUsuario" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="idProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_ClienteProducto" Member="Usuario" ThisKey="nombreUsuario" OtherKey="nombreUsuario" Type="Usuario" IsForeignKey="true" />
      <Association Name="producto_ClienteProducto" Member="producto" ThisKey="idProducto" OtherKey="idProducto" Type="producto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Persona.Cliente" Member="Cliente">
    <Type Name="Cliente">
      <Column Name="numeroIdentidad" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="apellido" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="fechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="fechaCreacion" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="correoElectronico" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="razon" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="peso" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="medidas" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_ClienteInscripcion" Member="ClienteInscripcion" ThisKey="numeroIdentidad" OtherKey="numeroIdentidad" Type="ClienteInscripcion" />
    </Type>
  </Table>
  <Table Name="Persona.Usuario" Member="Usuario">
    <Type Name="Usuario">
      <Column Name="nombreUsuario" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="constrasena" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_ClienteInscripcion" Member="ClienteInscripcion" ThisKey="nombreUsuario" OtherKey="nombreUsuario" Type="ClienteInscripcion" />
      <Association Name="Usuario_ClienteProducto" Member="ClienteProducto" ThisKey="nombreUsuario" OtherKey="nombreUsuario" Type="ClienteProducto" />
    </Type>
  </Table>
  <Table Name="Producto.Inscripcion" Member="Inscripcion">
    <Type Name="Inscripcion">
      <Column Name="idInscripcion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombreInscripcion" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="precioInscripcion" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Inscripcion_ClienteInscripcion" Member="ClienteInscripcion" ThisKey="idInscripcion" OtherKey="idInscripcion" Type="ClienteInscripcion" />
    </Type>
  </Table>
  <Table Name="Producto.producto" Member="producto">
    <Type Name="producto">
      <Column Name="idProducto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombreProducto" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="precioProducto" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="producto_ClienteProducto" Member="ClienteProducto" ThisKey="idProducto" OtherKey="idProducto" Type="ClienteProducto" />
    </Type>
  </Table>
</Database>